# Generated by Django 5.1.3 on 2024-12-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='uploaded_images/')),
                ('image_caption', models.CharField(blank=True, max_length=300, null=True)),
                ('story_text', models.TextField(blank=True, null=True)),
                ('story_audio', models.FileField(blank=True, null=True, upload_to='audio_files')),
            ],
        ),
    ]
